modLoader="javafml"
loaderVersion="${mod_loader_version}"
license="All rights reserved"

[[mods]]
    modId="${mod_id}"
    version="${mod_version}"
    displayName="${mod_name}"
    authors="${mod_vendor}"
    description='''Flux Pylons'''

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${mod_forge_version}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="[${mod_minecraft_version}]"
    ordering="NONE"
side="BOTH"
[[dependencies.${mod_id}]]
    modId="jei"
    mandatory=false
    versionRange="${jei_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="mekanism"
    mandatory=false
    versionRange="${mod_mekanism_version_range}"
    ordering="AFTER"
    side="BOTH"
